name: Build and test Python package

# adapted from https://github.com/mkoeppe/sage-numerical-backends-coin
on: [push, pull_request]

jobs:
  conda_sage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        environment: ["", -python2]
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sage-nim${{ matrix.environment }}
        environment-file: environment${{ matrix.environment }}.yml
        auto-activate-base: false
    - name: Show conda info
      shell: bash -l {0}
      run: conda list
    - name: Patch in CoinBackend
      shell: bash -l {0}
      run: sage -c 'import os; import sage.numerical.backends as dm; import sage_numerical_backends_coin.coin_backend as sm; s = sm.__file__; f = os.path.basename(s); d = os.path.join(dm.__path__[0], f); (os.path.exists(d) or os.path.lexists(d)) and os.remove(d); os.symlink(s, d);'
    - name: Test package
      shell: bash -l {0}
      run: tox
  ubuntu_sage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SageMath and CBC
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update || echo Warning... update error
        sudo DEBIAN_FRONTEND=noninteractive apt-get install sagemath coinor-cbc coinor-libcbc-dev python-setuptools python-sphinx tox python-pip
        sage -python -m pip install --user -r requirements.txt
    - name: Patch in CoinBackend
      run: sage -c 'import os; import sage.numerical.backends as dm; import sage_numerical_backends_coin.coin_backend as sm; s = sm.__file__; f = os.path.basename(s); d = os.path.join(dm.__path__[0], f); (os.path.exists(d) or os.path.lexists(d)) and os.remove(d); os.symlink(s, d);'
    - name: Test package
      run: tox
